### ISSUE TITLE
Missing dep on pkginfo>1.5.0

### ISSUE THREAD

**Issue by amyreese** [python-packaging/highlighter#2]

**Comment by thatch** [comment]
I don't think that `highlighter` needs this; it only depends on `packaging`.  Can you detail a little more?

The other one you filed, https://github.com/python-packaging/dowsing/issues/1 , is a real issue; that imports pkginfo.

**Comment by amyreese** [comment]
Yep, this was my fault for associating the failures in the wrong project.
